{{- if and (not .Values.clickhouse.initdb.existingSecret) .Values.clickhouse.initdb.scripts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.initdbSecretName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  {{- range $key, $value := .Values.clickhouse.initdb.scripts }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}