{{- if and (not .Values.clickhouse.additionalUsers.existingSecret) .Values.clickhouse.additionalUsers.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.usersdSecretName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  {{ .Values.clickhouse.additionalUsers.secretKey }}: {{ .Values.clickhouse.additionalUsers.content | b64enc }}
{{- end }}