{{- if and .Values.keeper.enabled .Values.keeper.auth.enabled .Values.keeper.auth.createSecret }}
{{- $username := .Values.keeper.auth.username }}
{{- $password := .Values.keeper.auth.password }}
{{- if and $username $password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.keeperAuthSecretName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
type: Opaque
data:
  {{ .Values.keeper.auth.secretKey }}: {{ printf "%s:%s" $username $password | b64enc }}
{{- else }}
{{- fail "Username and password must be provided when Keeper auth is enabled and createSecret is true" }}
{{- end }}
{{- end }}