{{- if and .Values.keeper.enabled .Values.keeper.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}-keeper-metrics
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
  {{- with .Values.keeper.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keeper
  ports:
    - name: http-metrics
      port: {{ .Values.ports.keeper.metrics }}
      targetPort: http-metrics
{{- end }}