apiVersion: v2
name: clickhouse
version: 0.3.8
appVersion: 25.12.3-alpine
description: A Helm chart for deploying ClickHouse with optional ClickHouse Keeper
type: application
home: https://clickhouse.com/
icon: https://brandfolder.com/clickhouse/media-kit/#!asset/tr4p5mpvnbf8fbbpmn9x
keywords:
  - clickhouse
  - database
  - analytics
maintainers:
  - name: calebhansard
sources:
  - https://github.com/ClickHouse/ClickHouse
  - https://github.com/korax-dev/clickhouse-k8s
